DatabaseConsistencySettings:
  color: true
  # log_level: DEBUG

# See issue for details why this checks are disabled.
# https://github.com/djezzzl/database_consistency/issues/36
User:
  email:
    ColumnPresenceChecker:
      enabled: false
  uid:
    ColumnPresenceChecker:
      enabled: false
  lower(email)+provider:
    MissingUniqueIndexChecker:
      enabled: false

ActiveStorage::Blob:
  enabled: false
ActiveStorage::Attachment:
  enabled: false

RailsSettings::Base:
  enabled: false
