kind: pipeline
name: default

steps:
- name: app
  image: chrztoph/texterify:1
  commands:
  - bin/rails db:create
  - bin/rails db:migrate
  - bin/rails db:seed
  - bin/rails test

services:
- name: postgres
  image: postgres
