kind: pipeline
name: default

steps:
- name: build
  image: plugins/docker
  settings:
    username:
      from_secret: DOCKER_USERNAME
    password:
      from_secret: DOCKER_PASSWORD
    repo: chrztoph/texterify
    tags: test

- name: app
  image: chrztoph/texterify:test
  commands:
  - bin/rails db:create
  - bin/rails db:migrate
  - bin/rails db:seed
  - SECRET_KEY_BASE=`bin/rails secret` bin/rails test

services:
- name: postgres
  image: postgres
