# See https://github.com/bbatsov/rubocop.

require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.7.1

Rails:
  Enabled: true

Rails/IndexBy:
    Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Style/HashEachMethods:
  Enabled: false

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/RedundantReturn:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

# Disabled because of pundit headless policies
Style/StructInheritance:
  Enabled: false

Style/BlockComments:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: "indented"

Layout/LineLength:
  Enabled: false

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Naming/FileName:
  Exclude:
    - Gemfile

RSpec/InstanceVariable:
    Enabled: false

RSpec/DescribedClass:
    Enabled: false

RSpec/HookArgument:
    EnforcedStyle: each

RSpec/RepeatedExample:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false
