language: ruby

env:
  global:
    - SECRET_KEY_BASE=8dfc55709e6daaf5d7b2ce70e247374400f47db2e4b6867f67821290b440a0acbe931d5f4d9687f386e5aae3f0377da533450058e131b37dbc16b692c296c941

services:
  - docker

install:
  - docker-compose up -d
  - docker-compose exec app bundle exec rails db:create db:migrate RAILS_ENV=test

script:
  - docker-compose exec app bin/rails test

after_success:
  - docker_login_response = echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ $docker_login_response != "Login succeeded"]; then
      exit 1
    fi

  # The chrztoph/texterify:${TRAVIS_COMMIT} tag is created with docker-compose.
  # Push to docker registry.
  - docker push chrztoph/texterify:${TRAVIS_COMMIT}

  # Tag the master as latest.
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
      docker tag chrztoph/texterify:${TRAVIS_COMMIT} chrztoph/texterify:latest
    fi
