language: ruby

env:
  global:
    - SECRET_KEY_BASE=8dfc55709e6daaf5d7b2ce70e247374400f47db2e4b6867f67821290b440a0acbe931d5f4d9687f386e5aae3f0377da533450058e131b37dbc16b692c296c941
    - DB_TEST_HOST=db
    - DB_TEST_USERNAME=postgres
    - secure: "VjnyyhXtm9o04EPw8uWXUOkfOFxM1U0t2/tUu3wd3AEGSOwBX6m8fyEcew85r3Vy2wPxznjORVGOHHvZ21XpPfOiCrtZWUXoHbezE0hMEaNAQUtZjo/wPiWGBdUBXcW8IcCOrOftrPkARYzezSkCjk2YXxZG74AUyLHcxDanS6kz7ZHlgbqmWW4YKd6GsQYgjAA4TNXoS9eikoP//KNcNZP1fPLgEx9Tc1XyTfJ53IIZc/QxvLd6rJgiNpLoRB/uPF3WuOP2SlCm1YDJbDH/0BY0mPMoW5FaeaWlGMz9/ZF7c0D8gYiiN7Ots5WsrRLFWWXTzp09nQssp1QV4IbcnUAgc5sXYOzoXs8OPGMJRW6i7E5r0Jy9dG7+0taYWHuIMX0AuXfsy0s/Z3YvE10UsC3By8OVqZo3U/Q185lRic2KJLLBTWomhcxAc5vDBAm+qQtXwaW5OwTXwPhiAll5O6uzbyfDqS1GjBvEEZAqXHGSQQerYD1/9qRwItUe96ug6LJzLktI/uNaGAimZKXSV80+Egzjo3qIHm2ERtg7jvFVOwKyMAdQQeXf9t8syP8D2z5qmS8XFJVL3ESfxsKGAUKRJCwVE5MHQsYVu87Cy9itih4TeRJxYIFOsjfV6bIGQvdxhPFySA/F+bRrkjXJphEjb7MqTx4j2z/eAMyBDIQ="
    - secure: "C1QS221YEjjDvUyXgsMKygOdi2nvd13BxfnSmN69gCjgx8NLaBwke5l7DSxmTYhND3Pcl32JXEyMqbBmbxD2TXNJDP38qJa0XXbsX5H1fyXKAz9Qe28qrEQ493WzX6GbqVwX4EAaDwogym0boA60x5TmZWpbco5yV1CI/TSZla5A8tPH8vYl6zUGF1rt7KTeD+6nh6H27yNVCQgiKSQ8Zh+zAOlC1nyjCje+KeUy4mtm4/VonrZp5QzkAWYgjh3QNELV9rHGLOJvGO5SsYRSO9Z77wbzp/IWeS8XAb73AXo8xh3qK9/2uKGRCcz9HJokgAuE892jTEueWPzJ1wWpconF54yDoeVjdZwh3MdLVd0MOZUBDkFJAznC7ElA9hFDLeSkWi86seDOeqJTQvL9uq6dgE7yLzpYlmNXSq7V3Pibn/H3UYU3v2OMQcrpPFfzyIjNhZ2AkuryOaC0VTZjDaLOieeEjmaVnH1Cxyl15mne4PBPhdISyvGgi33iuw9AcDBy3UOeENqtBQ0jPBXaz3Q7OCBAud+MLfzTHG9H0PcDmXM7sJsXFBXNiyWt8YNa1rpZsLJalA6yd38RoCUWt+9mHNFdAiSwR/FGhpsre9mMvQ9uWOQI2Sbfli/URP9eRXKUkwLgrD7hx1qumkhf99jgDzfC8kzGKWWkjFybLjk="

services:
  - docker

install:
  - docker-compose up -d
  - docker-compose exec app bundle exec rails db:create db:migrate db:seed RAILS_ENV=test
  - docker-compose exec app bundle install --with test

script:
  - docker-compose exec app yarn lint
  - docker-compose exec app yarn test
  - docker-compose exec app yarn check:database-consistency:test
  - docker-compose exec app bundle exec rails db:drop RAILS_ENV=test

after_success:
  # Setup ssh.
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key
  - ssh-add .travis/deploy_key

  # Tag the master as latest.
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
      echo "Pushing to docker..."

      # Login to docker.
      if echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>&1 | grep --quiet --ignore-case 'error'; then
        exit 1
      fi

      # The chrztoph/texterify:${TRAVIS_COMMIT} tag is created with docker-compose.
      # Push to docker registry.
      docker push chrztoph/texterify:${TRAVIS_COMMIT}

      # Create latest tag.
      docker tag chrztoph/texterify:${TRAVIS_COMMIT} chrztoph/texterify:latest
      docker push chrztoph/texterify:latest
    fi
