language: ruby

env:
  global:
    - SECRET_KEY_BASE=8dfc55709e6daaf5d7b2ce70e247374400f47db2e4b6867f67821290b440a0acbe931d5f4d9687f386e5aae3f0377da533450058e131b37dbc16b692c296c941
    - DB_TEST_HOST=db
    - DB_TEST_USERNAME=postgres
    - POSTGRES_HOST_AUTH_METHOD=trust

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_4cce2d48b512_key -iv $encrypted_4cce2d48b512_iv -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
  - tar xvf .travis/secrets.tar -C .travis

install:
  - docker-compose up -d
  - docker-compose exec app bundle exec rails db:create db:migrate db:seed RAILS_ENV=test
  - docker-compose exec app bundle install --with test

script:
  - docker-compose exec app yarn lint
  - docker-compose exec app yarn test
  - docker-compose exec app yarn check:database-consistency:test
  - docker-compose exec app bundle exec rails db:drop RAILS_ENV=test

after_success:
  # Setup ssh.
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/deploy_key
  - ssh-add .travis/deploy_key

  # Tag the master as latest.
  - |
    if [ $TRAVIS_BRANCH == "master" ] && [ $TRAVIS_PULL_REQUEST == "false" ]; then
      echo "Pushing to docker..."

      # Login to docker.
      if echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin 2>&1 | grep --quiet --ignore-case 'error'; then
        exit 1
      fi

      # The chrztoph/texterify:${TRAVIS_COMMIT} tag is created with docker-compose.
      # Push to docker registry.
      docker push chrztoph/texterify:${TRAVIS_COMMIT}

      # Create latest tag.
      docker tag chrztoph/texterify:${TRAVIS_COMMIT} chrztoph/texterify:latest
      docker push chrztoph/texterify:latest
    fi
