version: '3'
volumes:
  database: {}
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - database:/var/lib/postgresql/data
  app:
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_TEST_HOST=${DB_TEST_HOST}
      - DB_TEST_USERNAME=${DB_TEST_USERNAME}
      - SENTRY_AUTH_TOKEN=${SENTRY_AUTH_TOKEN}
      - SENTRY_ORGANIZATION_BACKEND=${SENTRY_ORGANIZATION_BACKEND}
      - SENTRY_PROJECT_BACKEND=${SENTRY_PROJECT_BACKEND}
    image: chrztoph/texterify:${TRAVIS_COMMIT}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
