version: '3'
volumes:
  texterify-database: {}
services:
  db:
    image: postgres
    volumes:
      - texterify-database:/var/lib/postgresql/data
  app:
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    image: chrztoph/texterify:${TRAVIS_COMMIT}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
