version: '3'
volumes:
  database: {}
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data
  app:
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - EMAIL_CONFIRMATION_REQUIRED=${EMAIL_CONFIRMATION_REQUIRED}
      - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
      - SMTP_ADDRESS=${SMTP_ADDRESS}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_DOMAIN=${SMTP_DOMAIN}
      - SMTP_USER_NAME=${SMTP_USER_NAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_ENABLE_STARTTLS_AUTO=${SMTP_ENABLE_STARTTLS_AUTO}
      - SMTP_OPENSSL_VERIFY_MODE=${SMTP_OPENSSL_VERIFY_MODE}
      - DB_TEST_HOST=${DB_TEST_HOST}
      - DB_TEST_USERNAME=${DB_TEST_USERNAME}
    image: chrztoph/texterify:${TRAVIS_COMMIT}
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
