version: '3'
volumes:
  database: {}
services:
  db:
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    image: postgres:12.2
    volumes:
      - database:/var/lib/postgresql/data
  app:
    environment:
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - DB_TEST_HOST=${DB_TEST_HOST}
      - DB_TEST_USERNAME=${DB_TEST_USERNAME}
    image: chrztoph/texterify:${COMMIT_HASH}
    build:
      context: .
      args:
        SENTRY_SOURCE_MAPS_AUTH_TOKEN: ${SENTRY_SOURCE_MAPS_AUTH_TOKEN}
        SENTRY_SOURCE_MAPS_ORGANIZATION: ${SENTRY_SOURCE_MAPS_ORGANIZATION}
        SENTRY_SOURCE_MAPS_PROJECT: ${SENTRY_SOURCE_MAPS_PROJECT}
        COMMIT_HASH: ${COMMIT_HASH}
      dockerfile: Dockerfile
    depends_on:
      - db
