# To start sidekiq run "bundle exec sidekiq".

:dynamic: true
:schedule:
  TrialEndingWorker:
    cron: '0 4 * * *' # "At 04:00."

  DeeplSupportedLanguagesWorker:
    cron: '0 4 * * *' # "At 04:00."
