name: Build & Push

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-latest
        env:
          COMMIT_HASH: $GITHUB_SHA
          DB_TEST_HOST: db
          DB_TEST_USERNAME: postgres
          SECRET_KEY_BASE: 8dfc55709e6daaf5d7b2ce70e247374400f47db2e4b6867f67821290b440a0acbe931d5f4d9687f386e5aae3f0377da533450058e131b37dbc16b692c296c941
        steps:
            - uses: actions/checkout@v2
            - name: Run docker-compose
              run: docker-compose up -d
            - name: Create and seed test database
              run: docker-compose exec app bundle exec rails db:create db:migrate db:seed RAILS_ENV=test
            - name: Install test dependencies
              run: docker-compose exec app bundle install --with test
            - name: Run linters
              run: docker-compose exec app yarn lint
            - name: Run tests
              run: docker-compose exec app yarn test
            - name: Check database consistency
              run: docker-compose exec app yarn check:database-consistency:test
              # run: docker-compose exec app bundle exec rails db:drop RAILS_ENV=test

    build-and-push:
        runs-on: ubuntu-latest
        needs: [test]
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        steps:
            - uses: actions/checkout@v2
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag chrztoph/texterify:$COMMIT_HASH
            - name: Tag image also as latest
              run: docker tag chrztoph/texterify:$COMMIT_HASH chrztoph/texterify:latest
            - name: Push images
              run: |
                  docker push chrztoph/texterify:$COMMIT_HASH
                  docker push chrztoph/texterify:latest
