name: Build & Push

on:
    push:
        branches: [master]

jobs:
    test:
        runs-on: ubuntu-18.04
        env:
          DB_TEST_HOST: db
          DB_TEST_USERNAME: postgres
          SECRET_KEY_BASE: 8dfc55709e6daaf5d7b2ce70e247374400f47db2e4b6867f67821290b440a0acbe931d5f4d9687f386e5aae3f0377da533450058e131b37dbc16b692c296c941
        steps:
            - uses: actions/checkout@v2

            # Pull the latest image to build, and avoid caching pull-only images.
            # (docker pull is faster than caching in most cases.)
            - run: docker-compose pull

            # In this step, this action saves a list of existing images,
            # the cache is created without them in the post run.
            # It also restores the cache if it exists.
            - uses: satackey/action-docker-layer-caching@v0.0.11
              # Ignore the failure of a step and avoid terminating the job.
              continue-on-error: true

            - name: Run docker-compose
              run: docker-compose up -d
            - name: Create and seed test database
              run: docker-compose exec -T app bundle exec rails db:create db:migrate db:seed RAILS_ENV=test
            - name: Install test dependencies
              run: docker-compose exec -T app bundle install --with test
            - name: Run linters
              run: docker-compose exec -T app yarn lint
            - name: Run tests
              run: docker-compose exec -T app yarn test
            - name: Check database consistency
              run: docker-compose exec -T app yarn check:database-consistency:test
            - name: Show disk space
              run: df -h
              # run: docker-compose exec -T app bundle exec rails db:drop RAILS_ENV=test

    build-and-push:
        runs-on: ubuntu-18.04
        needs: [test]
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        steps:
            - uses: actions/checkout@v2
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag chrztoph/texterify:$GITHUB_SHA
            - name: Tag image also as latest
              run: docker tag chrztoph/texterify:$GITHUB_SHA chrztoph/texterify:latest
            - name: Push images
              run: |
                  docker push chrztoph/texterify:$GITHUB_SHA
                  docker push chrztoph/texterify:latest
