name: Report

on:
  workflow_call:

jobs:
  report:
    runs-on: ubuntu-22.04
    steps:
      - name: Send notification to Slack if job fails
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: failure()
