name: Test

on:
  push:
    branches:
      - "**"
      - "!master"
      - "!beta"

jobs:
  test:
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit

  report:
    uses: ./.github/workflows/report.yml
    secrets: inherit
